version: 2

updates:
  - package-ecosystem: uv
    directory: /src/liquidctl_server
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore'
      include: 'scope'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    commit-message:
      prefix: 'chore'
      include: 'scope'
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
      semantic-release:
        patterns:
          - 'semantic-release'
          - '@semantic-release/*'
          - 'conventional-changelog-*'
