name: Build

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - src/**/*
      - .github/workflows/*.yaml

jobs:
  changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            src:
              - 'src/FanControl.Liquidctl/**'
              - 'src/liquidctl_server/**'

  checks:
    name: Quality Checks
    uses: ./.github/workflows/checks.yaml
    permissions:
      checks: write
      pull-requests: write

  build:
    name: Build
    needs: [changes, checks]
    if: needs.changes.outputs.src == 'true'
    runs-on: windows-latest
    outputs:
      artifact-name: ${{ steps.set-artifact-name.outputs.artifact-name }}
    steps:
      - name: Set Artifact Name
        id: set-artifact-name
        run: |
          $artifactName = "FanControl.Liquidctl-PR-${{ github.event.pull_request.number }}"
          echo "artifact-name=$artifactName" >> $env:GITHUB_OUTPUT

      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
        with:
          dotnet-version: "10.0.x"

      - name: Install Python
        uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
        with:
          python-version: "3.14"

      - name: Install uv
        uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0

      - name: Cache Nuitka
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            ~\AppData\Local\Nuitka\Nuitka
            ~\.cache\Nuitka
          key: nuitka-${{ runner.os }}-${{ github.sha }}
          restore-keys: |
            nuitka-${{ runner.os }}-

      - name: Build and Archive
        run: pwsh ./scripts/release.ps1

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: ${{ steps.set-artifact-name.outputs.artifact-name }}
          path: |
            FanControl.Liquidctl.zip
          retention-days: 30
